let ejemplo = {
  direccionComprador: 'Plaza Central, Avenida Santacoloma Local 2 Santiago,\u00a0Veraguas',
  ruex: null,
  nim: null,
  concentradoGranel: null,
  origen: null,
  puertoTransito: null,
  puertoDestino: 'AEROPUERTO INTERNACIONAL TOCUMEN',
  codigoPais: 135,
  incoterm: 'CIP',
  tipoCambioANB: null,
  numeroLote: null,
  fechaEmision: '2025-09-09T08:56:54.813',
  codigoMoneda: 2,
  montoTotalMoneda: 5584.7,
  montoTotal: 38869.51,
  montoTotalSujetoIva: 38869.51,
  numeroFactura: 7263,
  nombreRazonSocial: 'GREEN PEARL CORPORATION',
  codigoTipoDocumentoIdentidad: 4,
  numeroDocumento: '50683840453',
  complemento: null,
  codigoCliente: '6509',
  tipoCambio: '6.96',
  codigoMetodoPago: 5,
  numeroTarjeta: null,
  codigoLeyenda: 2483,
  usuario: 'EXPORTACION SEFO SAM',
  codigoDocumentoSector: null,
  codigoPuntoVenta: 0,
  montoDetalle: 4350,
  incotermDetalle: 'AEROPUERTO INTERNACIONAL TOCUMEN',
  totalGastosNacionalesFob: 5584.7,
  totalGastosInternacionales: 0,
  numeroDescripcionPaquetesBultos: '10 BULTOS DE POLIPROPILENO 30 kg',
  informacionAdicional: 'LOTE: 136',
  lugarDestino: 'Veraguas',
  detalles: [
    {
      codigoProducto: 'EXP-LG-003',
      codigoActividadSin: '011000',
      descripcion: 'Semilla de Desmodium heterocarpon var Maquenque',
      codigoProductoSin: '99100',
      cantidad: 300,
      precioUnitario: 14.5,
      subTotal: 4350,
      unidadMedida: 22,
      codigoNandina: '1209.29.00.00',
      montoDescuento: 0,
    },
  ],
  costosGastosNacionales: [
    {
      campo: 'TR\u00c1MITES Y OTROS',
      valor: 120,
    },
    {
      campo: 'SEGURO INTERNACIONAL',
      valor: 120,
    },
    {
      campo: 'FLETE A\u00c9REO INTERNACIONAL',
      valor: 994.7,
    },
  ],
  costosGastosInternacionales: [],
  emailCliente: null,
  cafc: null,
  codigoExcepcion: null,
  descuentoAdicional: 0,
  extras: {
    facturaTicket: '15c463e94a557b9152738f84d92b3b92fde5dbf5',
  },
}
export default ejemplo
let a = {
  numeroFactura: '',
  nombreRazonSocial: 'Cliente varios R',
  codigoPuntoVenta: '107',
  fechaEmision: '2025-11-13T11:08:37.458Z',
  cafc: '',
  codigoExcepcion: '',
  descuentoAdicional: 0,
  montoGiftCard: 0,
  codigoTipoDocumentoIdentidad: '1',
  numeroDocumento: '4586511',
  complemento: '',
  codigoCliente: 'CLI_68fbf2c1e4ce8',
  codigoMetodoPago: '10',
  numeroTarjeta: '',
  montoTotal: '1.002.004500.00',
  codigoMoneda: 7,
  montoTotalMoneda: '1.002.004500.00',
  usuario: 'richard50',
  emailCliente: 'factura@yofinanciero.com',
  telefonoCliente: '0000000',
  extras: {
    facturaTicket: '',
  },
  codigoLeyenda: 248,
  tipoCambio: 6.96,
  direccionComprador: 'Dirección Genérica',
  puertoDestino: 'variansa',
  lugarDestino: 'Bolivia',
  codigoPais: 22,
  incoterm: 'variansa',
  incotermDetalle: 'variansa',
  totalGastosNacionalesFob: '1.004500.00',
  totalGastosInternacionales: '2.00',
  montoDetalle: '4500.00',
  costosGastosNacionales: [
    {
      campo: 'gasto Nacional',
      valor: '1.00',
    },
  ],
  costosGastosInternacionales: [
    {
      campo: 'gasto internacional',
      valor: '2.00',
    },
  ],
  numeroDescripcionPaquetesBultos: 'paquete',
  informacionAdicional: 'adcional',
  detalles: [
    {
      codigoProducto: '00001',
      codigoActividadSin: '',
      codigoProductoSin: '62143',
      descripcion: 'Samsung 5000',
      unidadMedida: '7',
      precioUnitario: '4500',
      subTotal: '4500.00',
      cantidad: 1,
      numeroSerie: '',
      montoDescuento: 0,
      numeroImei: '',
      codigoNandina: '',
    },
  ],
  pagosDivididos: [
    {
      metodoPago: null,
      monto: 0,
      porcentaje: 0,
    },
  ],
}
console.log(a)
