let a = {
  numeroFactura: '',
  nombreRazonSocial: 'Cliente varios R',
  codigoPuntoVenta: '107',
  fechaEmision: '2025-11-13T11:08:37.458Z',
  cafc: '',
  codigoExcepcion: '',
  descuentoAdicional: 0,
  montoGiftCard: 0,
  codigoTipoDocumentoIdentidad: '1',
  numeroDocumento: '4586511',
  complemento: '',
  codigoCliente: 'CLI_68fbf2c1e4ce8',
  codigoMetodoPago: '10',
  numeroTarjeta: '',
  montoTotal: '1.002.004500.00',
  codigoMoneda: 7,
  montoTotalMoneda: '1.002.004500.00',
  usuario: 'richard50',
  emailCliente: 'factura@yofinanciero.com',
  telefonoCliente: '0000000',
  extras: {
    facturaTicket: '',
  },
  codigoLeyenda: 248,
  tipoCambio: 6.96,
  direccionComprador: 'Dirección Genérica',
  puertoDestino: 'variansa',
  lugarDestino: 'Bolivia',
  codigoPais: 22,
  incoterm: 'variansa',
  incotermDetalle: 'variansa',
  totalGastosNacionalesFob: '1.004500.00',
  totalGastosInternacionales: '2.00',
  montoDetalle: '4500.00',
  costosGastosNacionales: [
    {
      campo: 'gasto Nacional',
      valor: '1.00',
    },
  ],
  costosGastosInternacionales: [
    {
      campo: 'gasto internacional',
      valor: '2.00',
    },
  ],
  numeroDescripcionPaquetesBultos: 'paquete',
  informacionAdicional: 'adcional',
  detalles: [
    {
      codigoProducto: '00001',
      codigoActividadSin: '',
      codigoProductoSin: '62143',
      descripcion: 'Samsung 5000',
      unidadMedida: '7',
      precioUnitario: '4500',
      subTotal: '4500.00',
      cantidad: 1,
      numeroSerie: '',
      montoDescuento: 0,
      numeroImei: '',
      codigoNandina: '',
    },
  ],
  pagosDivididos: [
    {
      metodoPago: null,
      monto: 0,
      porcentaje: 0,
    },
  ],
}
export default a
