let a = {
  ver: 'registroVenta',
  tipoventa: '3',
  idusuario: '03afdbd66e7929b125f8597834fa83a4',
  idempresa: 'c0c7c76d30bd3dcaefc96f40275bdc0a',
  idcliente: '1091',
  sucursal: '932',
  tipodoc: '1',
  nrodoc: '4586511',
  fecha: '2025-11-13',
  direccion: 'Dirección Genérica',
  puertodestino: 'des',
  lugardestino: 'Bolivia',
  incoterm: 'des',
  detalleincoterm: 'des',
  descripcionPB: 'des',
  infoadicional: 'des',
  puntoventa: '107',
  metodopago: '1',
  canal: '98',
  tipopago: 'contado',
  periodopersonalizado: '0',
  jsonDetalles: {
    listaProductos: [
      {
        idproductoalmacen: '3409',
        cantidad: 1,
        precio: '100',
        idstock: '5356',
        idporcentaje: '153',
        candiponible: '15',
        descripcion: 'Samsung 5000',
        descripcionAdicional: '',
        codigo: '00001',
        id: '3409',
        subtotal: 100,
        datosAdicionales: '62143--7-',
        despachado: 1,
      },
    ],
    listaProductosFactura: [
      {
        codigoProducto: '00001',
        codigoActividadSin: '',
        codigoProductoSin: '62143',
        descripcion: 'Samsung 5000',
        unidadMedida: '7',
        precioUnitario: '100',
        subTotal: '100.00',
        cantidad: 1,
        numeroSerie: '',
        montoDescuento: 0,
        numeroImei: '',
        codigoNandina: '',
      },
    ],
    listaFactura: {
      numeroFactura: '',
      nombreRazonSocial: 'Cliente varios R',
      codigoPuntoVenta: '107',
      fechaEmision: '2025-11-13T16:08:51.279Z',
      cafc: '',
      codigoExcepcion: '',
      descuentoAdicional: 0,
      montoGiftCard: 0,
      codigoTipoDocumentoIdentidad: '1',
      numeroDocumento: '4586511',
      complemento: '',
      codigoCliente: 'CLI_68fbf2c1e4ce8',
      codigoMetodoPago: '10',
      numeroTarjeta: '',
      montoTotal: 910,
      codigoMoneda: 7,
      montoTotalMoneda: 130,
      usuario: 'richard50',
      emailCliente: 'factura@yofinanciero.com',
      telefonoCliente: '0000000',
      extras: {
        facturaTicket: '',
      },
      codigoLeyenda: 248,
      tipoCambio: '7',
      direccionComprador: 'Dirección Genérica',
      puertoDestino: 'des',
      lugarDestino: 'Bolivia',
      codigoPais: 22,
      incoterm: 'des',
      incotermDetalle: 'des',
      totalGastosNacionalesFob: 130,
      totalGastosInternacionales: 0,
      montoDetalle: '100.00',
      costosGastosNacionales: [
        {
          campo: 'des',
          valor: '10.00',
        },
        {
          campo: 'des',
          valor: '20.00',
        },
      ],
      costosGastosInternacionales: [],
      numeroDescripcionPaquetesBultos: 'des',
      informacionAdicional: 'des',
      detalles: [
        {
          codigoProducto: '00001',
          codigoActividadSin: '',
          codigoProductoSin: '62143',
          descripcion: 'Samsung 5000',
          unidadMedida: '7',
          precioUnitario: '100',
          subTotal: '100.00',
          cantidad: 1,
          numeroSerie: '',
          montoDescuento: 0,
          numeroImei: '',
          codigoNandina: '',
        },
      ],
      pagosDivididos: [
        {
          metodoPago: null,
          monto: 0,
          porcentaje: 0,
        },
      ],
      montoTotalSujetoIva: 910,
    },
    idalmacen: 93,
    codigosinsucursal: '0',
    token:
      'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzMDAzMzUiLCJqdGkiOiJlMzQwNWJmODQ5ZjE4ZWNhMTcxYTU2OTM1NGE1NWI3YmE1MDE0MGJjNTFhMGQ5NzM3OTVjNjVhZTI3ODA5MjY0ODJmNDlkMmM5Mzk1YzI3ZCIsImlhdCI6MTc2MTk0MzY0OSwibmJmIjoxNzYxOTQzNjQ5LCJleHAiOjE3OTM0Nzk2NDgsInN1YiI6IiIsInNjb3BlcyI6W119.H6G_zByl5TnDlQ8o47OIjg8xDmuYd3d6TZQv8N3GMizKZH_lP3H8TPjuMMsiuRo_aEl-Jl47Pt-BTv6qDiZUpzpsopQuLonKKsSEUYtReJxov0CZqVRlIGpjYLEml4zPYZLtN0OFQ42myJKiq96YnVi1fZ1lYe6X1LrrgW61SlXN4yd3-UoJaxxge9qXaK09Jtq1Fsvrc3kVwZY23eJSF6gtPhkRX9aM9fBgONNcvA3eT0PoTTCixFMr4bEa6LBCViFx4GMDOgZkFwXb_nALp38PGeJW-4GkqwIMkHLdaAkJGX04B3rMlxvOoj5j74OEJwLID9e52JunECUakWrk26mFhhgzkg1XHr7LvRiItRrFgp4UyRqOil91J6GLSbVroSMTbIq01PRUZdWRPM1LlSEroGcGUbHnkVb0vUjthsVDbQwBh0LnM7cjILprN3_l7OOgTUMPoSMOqLM1as1hAlUBUe7aq-8UP5LTqjD90aVAGPcMgu0rPZGsBVeUcgXt4rVv_BSJ5gfX4jAPIkHx_vHrWr7IVFxL-N3sRvcKO--7-SSHtBBWkPC3ydtwvVS1IR8hBxK93vcIDLsgrU1fz26Z6wmNy_5eFA-ln9zmzcuUOsTAFD8DRJ0Rdp4c2kgCgLTP4r0HLmbQ1XlxgWLazZ5f4Kp3wBmo0x7sdMDP0CI',
    tipo: '1',
    iddivisa: 160,
    idcampana: 0,
    ventatotal: '100.00',
    subtotal: '100.00',
    descuento: 0,
    nropagos: 0,
    valorpagos: 0,
    dias: {
      label: 'Personalizado',
      value: 0,
    },
    fechalimite: '',
    pagosDivididos: [
      {
        metodoPago: null,
        monto: 0,
        porcentaje: 0,
      },
    ],
    variablePago: 'dividido',
    puntoVenta: '111',
    puntoVentaSin: '107',
  },
}
export default a
